### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by kocierik** [lucat1/visimp#54]
when I start vim, this warning appears

```
fidget.nvim will soon be rewritten. Please checkout the 'legacy' tag to avoid breaking changes.
Spawning language server with cmd: `lua-language-server` failed. The language server 
is either not installed, missing from PATH, or not executable.
```

**Comment by lucat1** [comment]
For the second issue: the error is caused by the `lua-language-server` cmd not being available. You can either install it via `:Mason` (although it should be automatic) or remove the lua language from your list of languages (basic support is provided in neovim by default, you probably don't need the LSP).

For the one regarding `fidget.nvim` I pushed the commit bc81cd170701462cdcdd16de0f28509eac15319d, which should solve the issue for now. We still should remove the fixed branch once `fidget.nvim` has been updated.
Please note you will have to remove the package and let `visimp` reinstall it for you. You can use:
```sh
$ rm -rf ~/.local/share/nvim/site/pack/paks/opt/fidget.nvim
```

**Comment by specialfish9** [comment]
Hi, I did the command (and it actually deleted the right stuff) and made visimp re-install the package, but I still have the warning by fidget :p

**Comment by specialfish9** [comment]
Yes i did
before and after actually

**Comment by lucat1** [comment]
Mhh odd. Can you give me the output of:
```
$ grep fidget ~/.local/share/nvim/site/pack/paks/start/visimp/lua/visimp/layers/lsp.lua
```

**Comment by specialfish9** [comment]
`{ 'j-hui/fidget.nvim', opt = true },
    vim.cmd('packadd fidget.nvim')
    get_module('fidget').setup()`

**Comment by specialfish9** [comment]
need another pakupdate i guess

**Comment by specialfish9** [comment]
I swear that i did pakupdate

**Comment by specialfish9** [comment]
![07-04-23--16-20-41](https://github.com/lucat1/visimp/assets/33939215/0fd9608b-2b45-4dfe-9bc7-6550f7c755f7)

**Comment by specialfish9** [comment]
ups i fell so dumb rn

I should have checked that before!

I guess that this will solve both my problem

([the other problem]( https://github.com/lucat1/visimp/issues/53#issuecomment-1620520275))
